### ISSUE TITLE
新版本的gf cli生成的模型文件,删除了不少函数.

### ISSUE THREAD

**Issue by yanllllk** [tiger1103/gfast#11]
这样重新生成模型后,有好几处直接调用delete findone的地方报错.
gentable的EditReq这个结构,写在了model文件里,gf gen model重新生成的时候,会被覆盖,导致编译出错.

**Comment by tiger1103** [comment]
不要直接在项目中生成覆盖，应在其他目录生成覆盖model与entity ,目前gf框架模型正在改版，加入dao相关...待稳定后框架将过渡到新特性。

**Comment by tiger1103** [comment]
已适配新版
