### ISSUE TITLE
两个不同的gfast项目，在同一个浏览器登录后，会发生权限冲突问题

### ISSUE THREAD

**Issue by zjlx** [tiger1103/gfast#14]
您好，我有两个项目都用的gfast开发的，现在遇到个问题，两个项目都在同一个浏览器里登录时，先登录的会被后登录的项目给顶掉，前面的那个项目会提示无权限需要重新登录，请问如何解决呢，是gtoken的那里的问题吗？

**Comment by tiger1103** [comment]
那是因为你用的同样的redis配置，同样的gtoken缓存配置，造成两个系统用的都是同一个缓存key，解决方式很多，最简单的改下CacheKey加上项目名前缀。还有，两个项目用同一个浏览器打开如果用的同一个域名不同端口，相当于cookie是共用的，所以删除一个项目下的cookie另一个的也被删了。

**Comment by zjlx** [comment]
哦哦，明白了，感谢
