### ISSUE TITLE
大神 我拉代码在本地后台菜单项-简单博客管理-日志管理无法无法打开

### ISSUE THREAD

**Issue by Fawkes-hub** [tiger1103/gfast#29]
点击的时候  控制台提示
`Error: Cannot find module './plugin/blog/classification/list'
    at o (chunk-09e67496.3d5711de.js:13)
    at r (chunk-09e67496.3d5711de.js:13)
    at app.0af133c8.js:1`
--- 
但是在你的demo后台地址上是可以打开的，大佬求把新的代码上传~~~

**Comment by tiger1103** [comment]
打包的静态文件没打包博客，下载前端ui 源码里面带有博客
