### ISSUE TITLE
gtoken同时使用的问题

### ISSUE THREAD

**Issue by zjxzjx54** [tiger1103/gfast#36]
我同时在一个电脑上跑两个gfast项目,配置不同的gtoken的信息,但是两个项目不能同时登录,不然会相互影响,提示用户信息验证失败,我用的gotken模式1,没用redis,难道是哪里还需要配置嘛?

**Comment by cn-ygf** [comment]
CacheKey和EncryptKey调整一下试试

**Comment by zjlx** [comment]
> 我同时在一个电脑上跑两个gfast项目,配置不同的gtoken的信息,但是两个项目不能同时登录,不然会相互影响,提示用户信息验证失败,我用的gotken模式1,没用redis,难道是哪里还需要配置嘛?

我是用的redis模式，解决办法就是两个项目使用不同的redis库就可以解决了，例如一个你用了1，另外一个用5就可以了。如果你是用的内存模式，那么两者的储存的key改一下名字让他们不相同，应该就可以解决了。

**Comment by Wyatex** [comment]
看样子像是gcache的问题，但是理论上两个不同的进程内存数据是隔离的，试试用gf2的gfast v3看看

**Comment by tiger1103** [comment]
使用内存缓存是隔离的，缓存是在不同内存块，不会互相影响。你看下是否浏览器端用的同一个域名造成token相互冲突，用不同浏览器或不同域名试一下。

**Comment by zjxzjx54** [comment]
已经解决了,估计就是同一个域名冲突造成的
