### ISSUE TITLE
新手提问，数据库咋搞啊

### ISSUE THREAD

**Issue by fenglinhuowu** [tiger1103/gfast#78]
我看到的数据库相关的配置如下
# Database.
database:
  logger:
    level:   "all"
    stdout:  true
    Path: "resource/log/sql"

  default:
    link:   "mysql:gfast3:gfast333@tcp(192.168.0.212:3306)/gfast-v32?charset=utf8mb4&parseTime=true&loc=Local"
    debug:  true
    charset: "utf8mb4" #数据库编码
    dryRun: false #空跑
    maxIdle: 10 #连接池最大闲置的连接数
    maxOpen: 10 #连接池最大打开的连接数
    maxLifetime: "30s" #(单位秒)连接对象可重复使用的时间长度
但是不知道如何去配置本地mysql。以前都是直接根据数据库名称去创建对应的数据库，这里没有看到数据库名字

**Comment by tiger1103** [comment]
link就是数据库配置，驱动:用户名:密码@tcp(ip:端口)/数据库名
可以看一下官方文档：https://goframe.org/pages/viewpage.action?pageId=1114245

**Comment by fenglinhuowu** [comment]
1楼的说明简单明了
