### ISSUE TITLE
修改个人用户修改出现类型错误的BUG

### ISSUE THREAD

**Issue by joyoes** [tiger1103/gfast#8]
![修改密码BUG](https://user-images.githubusercontent.com/16605854/95010995-fe1e7200-065f-11eb-9afd-73c63cfd6aca.png)
修改密码功能类型转换错误，我提供一下URL：/system/user/updatePwd
以下截图是我修改的两个地方，不知道正确不哈，反正调试能正常通过：
![1](https://user-images.githubusercontent.com/16605854/95016706-4604bf80-0687-11eb-92f9-eedda2a37414.png)
![2](https://user-images.githubusercontent.com/16605854/95016708-48671980-0687-11eb-9326-f9a52f9edce6.png)

**Comment by tiger1103** [comment]
已修复
