### ISSUE TITLE
混合验证码提示参数错误

### ISSUE THREAD

**Issue by fenglinhuowu** [tiger1103/gfast#80]
Captcha.go里面验证码里面 idKeyC, base64stringC, err = c.Generate() ，这里调用赋值c.Generate返回值赋给前面3个变量。
但是，在captcha.go里面该函数返回的是4个值。captcha.go代码如下：
func (c *Captcha) Generate() (id, b64s, answer string, err error) {
	id, content, answer := c.Driver.GenerateIdQuestionAnswer()
	item, err := c.Driver.DrawCaptcha(content)
	if err != nil {
		return "", "", "", err
	}
	err = c.Store.Set(id, answer)
	if err != nil {
		return "", "", "", err
	}
	b64s = item.EncodeB64string()
	return
}
这个咋搞

**Comment by HanHan666666** [comment]
我也遇到了一样的问题

**Comment by tiger1103** [comment]
新版本验证码多了个返回参数，已修复
